# このファイルは編集しないでください(デフォルトのConfigMapなどを定義しています)
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-tab-config
data:
  groups.yml: |
    # default settings for all groups, all groups will take properties from this section unless player's primary group overrides a specific setting
    _DEFAULT_:
      tabprefix: " %condition:vanish% &f%prefix%"
      tagprefix: ""
      customtabname: "%display_name%"
      customtagname: "%display_name%" # don't forget to enable unlimited nametag mode to make this one work
      tabsuffix: "%suffix%"
      tagsuffix: ""
  config.yml: |
    # Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml
    header-footer:
      enabled: true
      header:
      - '&7ようこそ、 &f%player% &7さん！'
      - '&8------------------------------------------------'
      - '&7PING: %condition:ping% &7ms'
      - '&7TPS: %condition:tps% &7/ 20.00'
      - '&7オンラインプレイヤー: &a%condition:safe_online%&7人'
      - '&7現在地: &d${CFG_POD_NAMESPACE}&f/&b${CFG_POD_NAME} &7- %player_world%'
      - '&7所持金: &f%money_formatted%'
      - '&8------------------------------------------------'
      footer:
      - 'Azisaba Network'
      per-server: {}
      disable-condition: '%world%=disabledworld|%server%=disabledserver'
    tablist-name-formatting:
      enabled: true
      anti-override: true
      disable-condition: '%world%=disabledworld|%server%=disabledserver'
    scoreboard-teams:
      enabled: true
      enable-collision: false
      invisible-nametags: false
      anti-override: true
      sorting-types:
      - PLACEHOLDER_HIGH_TO_LOW:%primary_group_weight%
      - PLACEHOLDER_A_TO_Z:%display_name%
      case-sensitive-sorting: false
      unlimited-nametag-mode:
        enabled: false
      can-see-friendly-invisibles: false
      disable-condition: ''
    global-playerlist:
      enabled: true
      display-others-as-spectators: false
      display-vanished-players-as-spectators: true
      isolate-unlisted-servers: false
      spy-servers:
      - spyserver1
      - spyserver2
      server-groups: {}
    belowname-objective:
      enabled: false
      number: '%health%'
      text: '&cHealth'
      disable-condition: '%world%=disabledworld|%server%=disabledserver'
      fancy-display-default: NPC
      fancy-display-players: '&c%health%'
    prevent-spectator-effect:
      enabled: true
    bossbar:
      enabled: false
      toggle-command: /bossbar
      remember-toggle-choice: false
      hidden-by-default: false
      bars:
        ServerInfo:
          style: PROGRESS
          color: '%animation:barcolors%'
          progress: '100'
          text: '&fWebsite: &bwww.domain.com'
    scoreboard:
      enabled: false
      toggle-command: /sb
      remember-toggle-choice: false
      hidden-by-default: false
      use-numbers: false
      static-number: 0
      delay-on-join-milliseconds: 0
      respect-other-plugins: true
      scoreboards:
        scoreboard1:
          title: Default
          lines:
          - '%animation:MyAnimation1%'
          - '&6My Stats:'
          - '* &eKills&7: &f%statistic_player_kills%'
          - '* &eDeaths&7: &f%statistic_deaths%'
          - '* &eHealth&7: &f%health%'
          - ''
          - '&6Personal Info:'
          - '* &bRank&7: &f%rank%'
          - '* &bPing&7: &f%ping%&7ms'
          - '* &bWorld&7: &f%world%'
          - '%animation:MyAnimation1%'
    placeholders:
      date-format: dd.MM.yyyy
      time-format: '[HH:mm:ss / h:mm a]'
      time-offset: 0
      register-tab-expansion: false
    placeholder-output-replacements: {}
    conditions:
      safe_online:
        conditions:
        - permission:essentials.vanish
        - permission:essentials.vanish.*
        - permission:essentials.vanish.see
        - permission:essentials.*
        type: OR
        true: '%player_count%'
        false: '%safe_player_count%'
      nick:
        conditions:
        - '%player%=%essentials_nickname%'
        true: '%player%'
        false: ~%essentials_nickname%
      afk:
        conditions:
        - '%essentials_afk%=true'
        true: '&6☽'
        false: '&a●'
      vanish:
        conditions:
        - '%essentials_vanished%=true'
        true: '&f○'
        false: '%condition:afk%'
      ping_worst:
        conditions:
        - '%ping%>=150'
        true: '&c%ping%'
        false: ''
      ping_bad:
        conditions:
        - '%ping%<150'
        true: '&e%ping%'
        false: '%condition:ping_worst%'
      ping_normal:
        conditions:
        - '%ping%<100'
        true: '&d%ping%'
        false: '%condition:ping_bad%'
      ping:
        conditions:
        - '%ping%<50'
        true: '&a%ping%'
        false: '%condition:ping_normal%'
      tps_bad:
        conditions:
        - '%tps%>18'
        true: '&e%tps_formatted%'
        false: '&c%tps_formatted%'
      tps_good:
        conditions:
        - '%tps%>19'
        true: '&a%tps_formatted%'
        false: '%condition:tps_bad%'
      tps:
        conditions:
        - '%tps%>20'
        true: '&b%tps_formatted%'
        false: '%condition:tps_good%'
    placeholderapi-refresh-intervals:
      default-refresh-interval: 500
      '%server_uptime%': 1000
      '%server_tps_1_colored%': 1000
      '%player_health%': 200
      '%player_ping%': 1000
      '%vault_prefix%': 1000
      '%rel_factionsuuid_relation_color%': 1000
    assign-groups-by-permissions: false
    use-primary-group: true
    primary-group-finding-list:
    - default
    debug: false
    mysql:
      enabled: false
      host: 127.0.0.1
      port: 3306
      database: tab
      username: user
      password: password
    use-bukkit-permissions-manager: true
    use-online-uuid-in-tablist: true
    per-world-playerlist:
      enabled: false
    layout:
      enabled: false
      direction: COLUMNS
      default-skin: mineskin:1753261242
      enable-remaining-players-text: true
      remaining-players-text: '... and %s more'
      layouts:
        default:
          fixed-slots:
          - '1|&3Website&f:'
          - 2|&bmyserver.net
          - '3|&8&m                       '
          - '4|&3Name&f:'
          - 5|&b%luckperms-prefix%a%player%
          - '7|&3Rank&f:'
          - '8|Rank: %group%'
          - '10|&3World&f:'
          - 11|&b%world%
          - '13|&3Time&f:'
          - 14|&b%time%
          - '21|&3Teamspeak&f:'
          - 22|&bts.myserver.net
          - '23|&8&m                       '
          - '41|&3Store&f:'
          - 42|&bshop.myserver.net
          - '43|&8&m                       '
          groups:
            staff:
              condition: permission:tab.staff
              slots:
              - 24-40
            players:
              slots:
              - 44-80
    permission-refresh-interval: 1000
    playerlist-objective:
      enabled: false
      value: '%ping%'
      disable-condition: '%world%=disabledworld|%server%=disabledserver'
      fancy-value: '&7Ping: %ping%'
    ping-spoof:
      enabled: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spigot-yml-v12
data:
  spigot.yml: |
    # This is the main configuration file for Spigot.
    # As you can see, there's tons to configure. Some options may impact gameplay, so use
    # with caution, and make sure you know what each option does before configuring.
    # For a reference for any variable inside this file, check out the Spigot wiki at
    # http://www.spigotmc.org/wiki/spigot-configuration/
    # 
    # If you need help with the configuration or have any questions related to Spigot,
    # join us at the IRC or drop by our forums and leave a post.
    # 
    # IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
    # Forums: http://www.spigotmc.org/
    
    config-version: 12
    settings:
      debug: false
      save-user-cache-on-stop-only: false
      sample-count: 12
      bungeecord: true
      player-shuffle: 0
      user-cache-size: 1000
      moved-wrongly-threshold: 0.0625
      moved-too-quickly-multiplier: 10.0
      log-villager-deaths: true
      timeout-time: 60
      restart-on-crash: true
      restart-script: ./start.sh
      netty-threads: 4
      attribute:
        maxHealth:
          max: 2048.0
        movementSpeed:
          max: 2048.0
        attackDamage:
          max: 2048.0
    messages:
      whitelist: You are not whitelisted on this server!
      unknown-command: Unknown command. Type "/help" for help.
      server-full: The server is full!
      outdated-client: Outdated client! Please use {0}
      outdated-server: Outdated server! I'm still on {0}
      restart: Server is restarting
    commands:
      log: true
      tab-complete: 0
      send-namespaced: true
      spam-exclusions:
      - /skill
      silent-commandblock-console: false
      replace-commands:
      - setblock
      - summon
      - testforblock
      - tellraw
    advancements:
      disable-saving: false
      disabled:
      - minecraft:story/disabled
    stats:
      disable-saving: false
      forced-stats: {}
    world-settings:
      default:
        verbose: true
        mob-spawn-range: 8
        hopper-amount: 1
        dragon-death-sound-radius: 0
        seed-village: 10387312
        seed-desert: 14357617
        seed-igloo: 14357618
        seed-jungle: 14357619
        seed-swamp: 14357620
        seed-monument: 10387313
        seed-shipwreck: 165745295
        seed-ocean: 14357621
        seed-outpost: 165745296
        seed-endcity: 10387313
        seed-slime: 987234911
        max-tnt-per-tick: 100
        end-portal-sound-radius: 0
        view-distance: default
        enable-zombie-pigmen-portal-spawns: true
        item-despawn-rate: 6000
        arrow-despawn-rate: 1200
        trident-despawn-rate: 1200
        wither-spawn-sound-radius: 0
        hanging-tick-frequency: 100
        zombie-aggressive-towards-villager: true
        nerf-spawner-mobs: false
        max-entity-collisions: 8
        merge-radius:
          exp: 3.0
          item: 2.5
        growth:
          cactus-modifier: 100
          cane-modifier: 100
          melon-modifier: 100
          mushroom-modifier: 100
          pumpkin-modifier: 100
          sapling-modifier: 100
          beetroot-modifier: 100
          carrot-modifier: 100
          potato-modifier: 100
          wheat-modifier: 100
          netherwart-modifier: 100
          vine-modifier: 100
          cocoa-modifier: 100
          bamboo-modifier: 100
          sweetberry-modifier: 100
          kelp-modifier: 100
        entity-activation-range:
          animals: 32
          monsters: 32
          raiders: 48
          misc: 16
          water: 16
          villagers: 32
          flying-monsters: 32
          villagers-work-immunity-after: 100
          villagers-work-immunity-for: 20
          villagers-active-for-panic: true
          tick-inactive-villagers: true
          wake-up-inactive:
            animals-max-per-tick: 4
            animals-every: 1200
            animals-for: 100
            monsters-max-per-tick: 8
            monsters-every: 400
            monsters-for: 100
            villagers-max-per-tick: 4
            villagers-every: 600
            villagers-for: 100
            flying-monsters-max-per-tick: 8
            flying-monsters-every: 200
            flying-monsters-for: 100
        entity-tracking-range:
          players: 48
          animals: 48
          monsters: 48
          misc: 32
          other: 64
        ticks-per:
          hopper-transfer: 8
          hopper-check: 1
        hunger:
          jump-walk-exhaustion: 0.05
          jump-sprint-exhaustion: 0.2
          combat-exhaustion: 0.1
          regen-exhaustion: 6.0
          swim-multiplier: 0.01
          sprint-multiplier: 0.1
          other-multiplier: 0.0
        max-tick-time:
          tile: 50
          entity: 50
        squid-spawn-range:
          min: 45.0
