# このファイルは簡易的な使い捨てMinecraftサーバーを建てるためのテンプレートです
# 「sandbox-test」の部分はすべて別の名前に置き換えてください
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-test
spec:
  selector:
    matchLabels:
      app: sandbox-test
  revisionHistoryLimit: 1 # 変更非推奨
  template:
    metadata:
      labels:
        app: sandbox-test
        stage: production # ここは変更しないでください
        kuvel.azisaba.net/enable-server-discovery: "true" # ここは変更しないでください
        kuvel.azisaba.net/preferred-server-name: sandbox-test # 「/server <ここの名前>」
    spec:
      containers:
      - name: sandbox-test
        # Dockerイメージの指定
        # java11の11の部分を8にしたり17にしたりなど、Minecraftバージョンによって適宜変えてください
        # Javaバージョン早見表
        # 1.14.4以下 ... 8
        # 1.15.x ... 8-11 (9-10はサポート終了)
        # 1.16.x ... 11-16 (12-16はサポート終了)
        # 1.17.x ... 16-17 (16はサポート終了)
        # 1.18.x～1.20.4 ... 17
        # 1.20.5以降 ... 21
        image: itzg/minecraft-server:java11
        workingDir: /data # 変更しないでください
        imagePullPolicy: Always # 変更非推奨
        resources:
          # メモリリクエスト (変更非推奨)
          requests:
            cpu: "1500m"
            memory: "1Gi"
          # メモリ制限 (変更非推奨)
          limits:
            cpu: "3000m"
            memory: "5Gi"
        ports:
          - containerPort: 25565 # 変更しないでください
        env:
          # タイムゾーン(変更非推奨)
          - name: TZ
            value: "Asia/Tokyo"
          # EULAに同意する(変更しないでください)
          - name: EULA
            value: "true"
          # サーバーの種類
          - name: TYPE
            value: PAPER
          # 最適化されたJVMフラグを使用する
          - name: USE_AIKAR_FLAGS
            value: "true"
          # スポーン保護
          - name: SPAWN_PROTECTION
            value: "0"
          # オンラインモード(変更しないでください)
          - name: ONLINE_MODE
            value: "false"
          # コマンドブロックを有効にする
          - name: ENABLE_COMMAND_BLOCK
            value: "true"
          # ネザーを有効にする
          - name: ALLOW_NETHER
            value: "false"
          # "Flying is not enabled on this server"を有効にする
          - name: ALLOW_FLIGHT
            value: "false"
          # 描画距離
          - name: VIEW_DISTANCE
            value: "10"
          # 統計情報をMojangに送信する
          - name: SNOOPER_ENABLED
            value: "false"
          # プレイヤーの実績・進捗解除を全体チャットに流す
          - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
            value: "false"
          # 最大人数
          - name: MAX_PLAYERS
            value: "1000"
          # UID (変更しないでください)
          - name: UID
            value: "0"
          # Minecraftバージョン
          - name: VERSION
            value: 1.15.2
          # 初期メモリ (変更非推奨)
          - name: INIT_MEMORY
            value: 1G
          # 最大メモリ (変更非推奨)
          - name: MAX_MEMORY
            value: 4G
          # ホワイトリスト
          - name: ENABLE_WHITELIST
            value: "false"
          # yml内のCFG_なんとかを置き換えるためのもの
          - name: ENV_VARIABLE_PREFIX
            value: "CFG_"
          # メタデータ(サーバー内で環境変数で取得可能)
          - name: CFG_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CFG_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # ここにプラグインのURLのリストを記載します
          # こちらもご覧ください(英語): https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/
          - name: PLUGINS
            value: |
              https://ci.viaversion.com/job/ViaVersion-Java8/14/artifact/build/libs/ViaVersion-5.0.3-downgraded.jar
              https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Java8/9/artifact/build/libs/ViaBackwards-5.0.3-downgraded.jar
              https://pub-9eecc53a1bf442f0a63c7f7342e5f66a.r2.dev/245e015b-e84e-4ec2-939b-e9b70a95316b/TAB-BukkitBridge-2.1.0.jar
              https://github.com/NEZNAMY/TAB/releases/download/4.1.7/TAB.v4.1.7.jar
              https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
              https://pub-9eecc53a1bf442f0a63c7f7342e5f66a.r2.dev/623659c0-fb71-4c69-bd28-a66b2fc20f09/SimpleShop-1.0.0.jar
        # ここから下は変更非推奨
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 20 # 200秒
          periodSeconds: 10
        volumeMounts:
        - name: spigot-yml
          mountPath: /data/spigot.yml
          subPath: spigot.yml
        - name: ops-json
          mountPath: /data/ops.json
          subPath: ops.json
        - name: common-tab-config
          mountPath: /plugins/TAB/config.yml
          subPath: config.yml
        - name: common-tab-config
          mountPath: /plugins/TAB/groups.yml
          subPath: groups.yml
        - name: shops-sandbox-test
          mountPath: /plugins/SimpleShop/config.yml
          subPath: config.yml
      volumes:
      - name: spigot-yml
        configMap:
          name: spigot-yml-v12
      - name: ops-json
        configMap:
          name: ops-json-sandbox-test
      - name: common-tab-config
        configMap:
          name: common-tab-config
      - name: shops-sandbox-test
        configMap:
          name: shops-sandbox-test
      priorityClassName: minecraft-other-server # ここは変更しないでください
      terminationGracePeriodSeconds: 60 # 1分
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-json-sandbox-test
data:
  # ops.jsonの内容
  # ここに記載されたプレイヤーはデフォルトでOP権限を持ちます
  # UUIDとMCIDを記載する必要がありますが、UUIDはNameMC等で調べたものを入れてください
  ops.json: |
    [
      {"uuid": "1865ab8c-700b-478b-9b52-a8c58739df1a", "name": "KotlinLove", "level": 4}
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shops-sandbox-test
data:
  config.yml: |
    layout:
    - null
    - null
    - null
    - null
    - "貴重品:BEACON"
    - null
    - null
    - null
    - null
    - "雑貨&ゴミ:STICK"
    - "鉱石:EMERALD"
    - "農作物+α:WHEAT"
    - "建材:STONE"
    - "色付きブロック系の建材:GLASS"
    - "木材:OAK_LOG"
    - "スポーンエッグ:ZOMBIE_SPAWN_EGG"
    - "装飾:HONEY_BLOCK"
    - "エンチャント:ENCHANTING_TABLE"
    shops:
      "農作物+α:WHEAT":
      - OAK_SAPLING;30;0
      - SPRUCE_SAPLING;30;0
      - BIRCH_SAPLING;30;0
      - JUNGLE_SAPLING;30;0
      - ACACIA_SAPLING;30;0
      - DARK_OAK_SAPLING;30;0
      - WHEAT_SEEDS;10;1
      - PUMPKIN_SEEDS;10;0
      - PUMPKIN;50;1
      - SUGAR_CANE;25;5
      - CACTUS;50;1
      - NETHER_WART;50;15
      - VINE;40;0
      - BROWN_MUSHROOM;0;30
      - RED_MUSHROOM;0;30
      - APPLE;20;5
      - MELON_SLICE;25;5
      - WHEAT;0;15
      - POTATO;0;15
      - CARROT;0;15
      - COD;0;25
      - SALMON;0;25
      - TROPICAL_FISH;0;30
      - PUFFERFISH;0;30
      "鉱石:EMERALD":
      - EMERALD;5000;5000
      - EMERALD_BLOCK;45000;45000
      - DIAMOND;5000;2000
      - DIAMOND_BLOCK;45000;18000
      - GOLD_INGOT;1400;400
      - GOLD_BLOCK;12600;3600
      - IRON_INGOT;800;300
      - IRON_BLOCK;7200;2700
      - COAL;300;100
      - COAL_BLOCK;2700;900
      - REDSTONE;60;30
      - REDSTONE_BLOCK;540;270
      - LAPIS_LAZULI;80;40
      - LAPIS_BLOCK;720;360
      "スポーンエッグ:ZOMBIE_SPAWN_EGG":
      - CREEPER_SPAWN_EGG;200000;0
      - SKELETON_SPAWN_EGG;200000;0
      - SPIDER_SPAWN_EGG;200000;0
      - ZOMBIE_SPAWN_EGG;200000;0
      - SLIME_SPAWN_EGG;400000;0
      - GHAST_SPAWN_EGG;600000;0
      - ZOMBIE_PIGMAN_SPAWN_EGG;200000;0
      - ENDERMAN_SPAWN_EGG;250000;0
      - CAVE_SPIDER_SPAWN_EGG;200000;0
      - BLAZE_SPAWN_EGG;300000;0
      - PIG_SPAWN_EGG;10000;0
      - COW_SPAWN_EGG;20000;0
      - SHEEP_SPAWN_EGG;10000;0
      - RABBIT_SPAWN_EGG;15000;0
      - HORSE_SPAWN_EGG;40000;0
      - LLAMA_SPAWN_EGG;10000;0
      - OCELOT_SPAWN_EGG;30000;0
      - WOLF_SPAWN_EGG;30000;0
      - PANDA_SPAWN_EGG;25000;0
      - POLAR_BEAR_SPAWN_EGG;30000;0
      - FOX_SPAWN_EGG;30000;0
      - TROPICAL_FISH_SPAWN_EGG;15000;0
      - CHICKEN_SPAWN_EGG;10000;0
      - DOLPHIN_SPAWN_EGG;40000;0
      - PARROT_SPAWN_EGG;40000;0
      "木材:OAK_LOG":
      - OAK_LOG;30;10
      - SPRUCE_LOG;30;10
      - BIRCH_LOG;30;10
      - JUNGLE_LOG;30;10
      - ACACIA_LOG;30;10
      - DARK_OAK_LOG;30;10
      - STRIPPED_OAK_LOG;50;15
      - STRIPPED_SPRUCE_LOG;50;15
      - STRIPPED_BIRCH_LOG;50;15
      - STRIPPED_JUNGLE_LOG;50;15
      - STRIPPED_ACACIA_LOG;50;15
      - STRIPPED_DARK_OAK_LOG;50;15
      - OAK_LEAVES;50;15
      - SPRUCE_LEAVES;50;15
      - BIRCH_LEAVES;50;15
      - JUNGLE_LEAVES;50;15
      - ACACIA_LEAVES;50;15
      - DARK_OAK_LEAVES;50;15
      "建材:STONE":
      - STONE_BRICKS;30;0
      - MOSSY_STONE_BRICKS;30;0
      - CRACKED_STONE_BRICKS;30;0
      - CHISELED_STONE_BRICKS;30;0
      - STONE;30;1
      - COBBLESTONE;30;1
      - MOSSY_COBBLESTONE;30;0
      - GRANITE;30;1
      - DIORITE;30;1
      - ANDESITE;30;1
      - MYCELIUM;40;0
      - PODZOL;40;0
      - GRASS;10;0
      - GRASS_BLOCK;20;0
      - DIRT;30;1
      - BRICKS;10;0
      - OAK_WOOD;20;0
      - SPRUCE_WOOD;20;0
      - BIRCH_WOOD;20;0
      - JUNGLE_WOOD;20;0
      - ACACIA_WOOD;20;0
      - DARK_OAK_WOOD;20;0
      - CLAY;20;0
      - OBSIDIAN;150;0
      - SANDSTONE;30;0
      - SAND;30;1
      - RED_SAND;30;0
      - GRAVEL;10;1
      - QUARTZ_BLOCK;30;0
      - CHISELED_QUARTZ_BLOCK;30;0
      - QUARTZ_PILLAR;30;0
      - SMOOTH_QUARTZ;30;0
      - NETHER_BRICK;30;0
      - NETHERRACK;30;5
      - RED_NETHER_BRICKS;30;0
      - SOUL_SAND;20;0
      - GLOWSTONE;20;0
      - SNOW_BLOCK;30;0
      - ICE;10;0
      - PACKED_ICE;10;0
      - BLUE_ICE;10;0
      - END_STONE;30;10
      - SCAFFOLDING;10;0
      - PRISMARINE;30;0
      - PRISMARINE_BRICKS;50;0
      - DARK_PRISMARINE;50;0
      - SMOOTH_STONE;30;0
      - SMOOTH_SANDSTONE;30;0
      - BROWN_MUSHROOM_BLOCK;40;0
      - RED_MUSHROOM_BLOCK;40;0
      - MUSHROOM_STEM;40;0
      "色付きブロック系の建材:GLASS":
      - GLASS;10;0
      - WHITE_STAINED_GLASS;20;0
      - ORANGE_STAINED_GLASS;20;0
      - MAGENTA_STAINED_GLASS;20;0
      - LIGHT_BLUE_STAINED_GLASS;20;0
      - YELLOW_STAINED_GLASS;20;0
      - LIME_STAINED_GLASS;20;0
      - PINK_STAINED_GLASS;20;0
      - GRAY_STAINED_GLASS;20;0
      - LIGHT_GRAY_STAINED_GLASS;20;0
      - CYAN_STAINED_GLASS;20;0
      - PURPLE_STAINED_GLASS;20;0
      - BLUE_STAINED_GLASS;20;0
      - BROWN_STAINED_GLASS;20;0
      - GREEN_STAINED_GLASS;20;0
      - RED_STAINED_GLASS;20;0
      - BLACK_STAINED_GLASS;20;0
      - WHITE_WOOL;20;0
      - ORANGE_WOOL;20;0
      - MAGENTA_WOOL;20;0
      - LIGHT_BLUE_WOOL;20;0
      - YELLOW_WOOL;20;0
      - LIME_WOOL;20;0
      - PINK_WOOL;20;0
      - GRAY_WOOL;20;0
      - LIGHT_GRAY_WOOL;20;0
      - CYAN_WOOL;20;0
      - PURPLE_WOOL;20;0
      - BLUE_WOOL;20;0
      - BROWN_WOOL;20;0
      - GREEN_WOOL;20;0
      - RED_WOOL;20;0
      - BLACK_WOOL;20;0
      - WHITE_CONCRETE;30;0
      - ORANGE_CONCRETE;30;0
      - MAGENTA_CONCRETE;30;0
      - LIGHT_BLUE_CONCRETE;30;0
      - YELLOW_CONCRETE;30;0
      - LIME_CONCRETE;30;0
      - PINK_CONCRETE;30;0
      - GRAY_CONCRETE;30;0
      - LIGHT_GRAY_CONCRETE;30;0
      - CYAN_CONCRETE;30;0
      - PURPLE_CONCRETE;30;0
      - BLUE_CONCRETE;30;0
      - BROWN_CONCRETE;30;0
      - GREEN_CONCRETE;30;0
      - RED_CONCRETE;30;0
      - BLACK_CONCRETE;30;0
      - WHITE_CONCRETE_POWDER;20;0
      - ORANGE_CONCRETE_POWDER;20;0
      - MAGENTA_CONCRETE_POWDER;20;0
      - LIGHT_BLUE_CONCRETE_POWDER;20;0
      - YELLOW_CONCRETE_POWDER;20;0
      - LIME_CONCRETE_POWDER;20;0
      - PINK_CONCRETE_POWDER;20;0
      - GRAY_CONCRETE_POWDER;20;0
      - LIGHT_GRAY_CONCRETE_POWDER;20;0
      - CYAN_CONCRETE_POWDER;20;0
      - PURPLE_CONCRETE_POWDER;20;0
      - BLUE_CONCRETE_POWDER;20;0
      - BROWN_CONCRETE_POWDER;20;0
      - GREEN_CONCRETE_POWDER;20;0
      - RED_CONCRETE_POWDER;20;0
      - BLACK_CONCRETE_POWDER;20;0
      - TERRACOTTA;20;0
      - WHITE_TERRACOTTA;30;0
      - ORANGE_TERRACOTTA;30;0
      - MAGENTA_TERRACOTTA;30;0
      - LIGHT_BLUE_TERRACOTTA;30;0
      - YELLOW_TERRACOTTA;30;0
      - LIME_TERRACOTTA;30;0
      - PINK_TERRACOTTA;30;0
      - GRAY_TERRACOTTA;30;0
      - LIGHT_GRAY_TERRACOTTA;30;0
      - CYAN_TERRACOTTA;30;0
      - PURPLE_TERRACOTTA;30;0
      - BLUE_TERRACOTTA;30;0
      - BROWN_TERRACOTTA;30;0
      - GREEN_TERRACOTTA;30;0
      - RED_TERRACOTTA;30;0
      - BLACK_TERRACOTTA;30;0
      "装飾:HONEY_BLOCK":
      - HONEY_BLOCK;30;0
      - HONEY_BOTTLE;30;0
      - HONEYCOMB;50;0
      - HONEYCOMB_BLOCK;50;0
      - BEEHIVE;50;0
      - END_ROD;40;0
      - FLOWER_POT;10;0
      - ARMOR_STAND;50;0
      - DAYLIGHT_DETECTOR;50;0
      - BREWING_STAND;1000;0
      - END_CRYSTAL;1500;0
      - DRAGON_BREATH;30;0
      - CREEPER_BANNER_PATTERN;300;0
      - GLOBE_BANNER_PATTERN;300;0
      - TUBE_CORAL_FAN;200;0
      - TUBE_CORAL;200;0
      - TUBE_CORAL_BLOCK;450;0
      - BRAIN_CORAL_FAN;200;0
      - BRAIN_CORAL;200;0
      - BRAIN_CORAL_BLOCK;450;0
      - BUBBLE_CORAL_FAN;200;0
      - BUBBLE_CORAL;200;0
      - BUBBLE_CORAL_BLOCK;450;0
      - FIRE_CORAL_FAN;200;0
      - FIRE_CORAL;200;0
      - FIRE_CORAL_BLOCK;450;0
      - HORN_CORAL_FAN;200;0
      - HORN_CORAL;200;0
      - HORN_CORAL_BLOCK;450;0
      - RED_DYE;20;0
      - GREEN_DYE;20;0
      - PURPLE_DYE;20;0
      - CYAN_DYE;20;0
      - LIGHT_GRAY_DYE;20;0
      - GRAY_DYE;20;0
      - PINK_DYE;20;0
      - LIME_DYE;20;0
      - YELLOW_DYE;20;0
      - LIGHT_BLUE_DYE;20;0
      - MAGENTA_DYE;20;0
      - ORANGE_DYE;20;0
      - BLUE_DYE;20;0
      - BROWN_DYE;20;0
      - BLACK_DYE;20;0
      - WHITE_DYE;20;0
      - SEA_PICKLE;200;0
      - DANDELION;100;0
      - POPPY;100;0
      - BLUE_ORCHID;100;0
      - ALLIUM;100;0
      - AZURE_BLUET;100;0
      - RED_TULIP;100;0
      - ORANGE_TULIP;100;0
      - WHITE_TULIP;100;0
      - PINK_TULIP;100;0
      - OXEYE_DAISY;100;0
      - CORNFLOWER;100;0
      - LILY_OF_THE_VALLEY;100;0
      - LILAC;100;0
      - ROSE_BUSH;100;0
      - PEONY;100;0
      - LANTERN;40;0
      - BELL;300;0
      - WITHER_ROSE;320;0
      - SEA_LANTERN;85;0
      - CAMPFIRE;100;0
      "雑貨&ゴミ:STICK":
      - STICK;0;1
      - COCOA_BEANS;0;1
      - GLOWSTONE_DUST;0;1
      - ROTTEN_FLESH;0;1
      - BONE;0;1
      - SPIDER_EYE;0;1
      - STRING;0;1
      - GUNPOWDER;0;1
      - SLIME_BALL;0;1
      - ENDER_PEARL;0;1
      - BLAZE_ROD;0;1
      - MUSIC_DISC_13;0;800
      - MUSIC_DISC_CAT;0;800
      - NAME_TAG;0;800
      - QUARTZ;0;1
      - FLINT;0;1
      - LEATHER;12;0
      - RABBIT_HIDE;3;0
      - ARROW;10;1
      - EGG;0;5
      - INK_SAC;25;0
      - NAUTILUS_SHELL;0;0
      "エンチャント:ENCHANTING_TABLE":
      - EXPERIENCE_BOTTLE;200;1
      - BOOKSHELF;100;0
      "貴重品:BEACON":
      - BEACON;1000000;50000
      - ELYTRA;1000000;50000
