# 「sandbox-test」の部分はすべて別の名前に置き換えてください
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-test
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: sandbox-test
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: sandbox-test
        stage: production # ここは変更しないでください (Don't change here!)
        kuvel.azisaba.net/enable-server-discovery: "true" # ここは変更しないでください (Don't change here!)
        kuvel.azisaba.net/preferred-server-name: sandbox-test
    spec:
      containers:
      - name: sandbox-test
        image: itzg/minecraft-server:java11
        workingDir: /data
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1500m"
            memory: "1Gi"
          limits:
            cpu: "3000m"
            memory: "4Gi"
        ports:
          - containerPort: 25565
        env:
          - name: TZ
            value: "Asia/Tokyo"
          - name: EULA
            value: "true"
          - name: TYPE
            value: PAPER
          - name: USE_AIKAR_FLAGS
            value: "true"
          - name: SPAWN_PROTECTION
            value: "0"
          - name: ONLINE_MODE
            value: "false" # ここは変更しないでください (Don't change here!)
          - name: ENABLE_COMMAND_BLOCK
            value: "true"
          - name: ALLOW_NETHER
            value: "false"
          - name: VIEW_DISTANCE
            value: "8"
          - name: SNOOPER_ENABLED
            value: "false"
          - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
            value: "false"
          - name: MAX_PLAYERS
            value: "1000"
          - name: UID
            value: "0"
          - name: VERSION
            value: 1.15.2
          - name: INIT_MEMORY
            value: 1G
          - name: MAX_MEMORY
            value: 4G
          - name: ENABLE_WHITELIST
            value: "false"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # ここにプラグインのURLのリストを記載します (Define plugins here)
          # こちらもご覧ください(英語) Also see: https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/
          - name: PLUGINS
            value: |
              https://ci.viaversion.com/job/ViaVersion-Java8/14/artifact/build/libs/ViaVersion-5.0.3-downgraded.jar
              https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Java8/9/artifact/build/libs/ViaBackwards-5.0.3-downgraded.jar
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 20 # 200 seconds
          periodSeconds: 10
        volumeMounts:
        - name: spigot-yml
          mountPath: /data/spigot.yml
          subPath: spigot.yml
        - name: ops-json
          mountPath: /data/ops.json
          subPath: ops.json
      volumes:
      - name: spigot-yml
        configMap:
          name: spigot-yml-v12
      - name: ops-json
        configMap:
          name: ops-json-sandbox-test
      priorityClassName: minecraft-other-server # ここは変更しないでください (Don't change here!)
      terminationGracePeriodSeconds: 60 # 1 minute
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-json-sandbox-test
data:
  ops.json: |
    [
      {"uuid": "1865ab8c-700b-478b-9b52-a8c58739df1a", "name": "KotlinLove", "level": 4}
    ]
